### ISSUE TITLE
How much time is expected to complete an instalation using conda?

### ISSUE THREAD

**Issue by ivopr** [alanwilter/acpype#100]
Well, as the title says, how much time should I expect to leave it running? Yesterday I gave up when it was about 13000 seconds.

Just to be sure, these are my pc specs:

Ryzen 5 4600G (6 cores, 12 threads)
24GB (16GB usable) DDR4 at 3200Mhz

Also, I was trying it on docker, with the `continuumio/miniconda3` image

**Comment by lkagami** [comment]
Dear user, the estimated installation time is less than 10 minutes.  I suggest you install the most current version of Anaconda and use the conda-forge repository to do the installation: conda install -c conda-forge acpype.
Thank you for use Acpype!
Regards,
Luciano

**Comment by lkagami** [comment]
why are you using anaconda in a docker image?

**Comment by ivopr** [comment]
I'm trying to use acpype programatically, and am trying to later deploy using a container, at the moment, this installation on a Dockerfile is the only remaining wall. All the code is already completed, Just this migration to a container remains.

**Comment by lkagami** [comment]
And did you try to use pip install?
