### ISSUE TITLE
Conda installs "full" ambertools, no writing of CHARMM ff files

### ISSUE THREAD

**Issue by jacksoncrowley** [alanwilter/acpype#101]
Hey!

I'm trying to generate CHARMM ff files alongside the rest of the output; however, my conda installation, performed as:
`conda create -n acpype`
`conda install -c conda-forge acpype`
Installs version 23.3 of ambertools, not the "stripped back" version (I see the explanation in Issue #14)
Any suggestions on how to modify the version of AmberTools without breaking the rest of the dependencies?

All the best, cheers!

**Comment by lkagami** [comment]
Dear user,
Unfortunately this is not possible, because the AmberTools package does not provide the charmmgen tool responsible for this conversion since version 17.  In our package, we added this tool to not lose this functionality.
Thanks for use ACPYPE!
Regards,
Luciano

**Comment by jacksoncrowley** [comment]
Okay, makes sense! Thanks for the explanation.
