### ISSUE TITLE
more water models from Amber

### ISSUE THREAD

**Issue by thepineapplepirate** [alanwilter/acpype#115]
Hi Alan,

Wondering if there are any plans to be able to handle more water models, such as Tip4pew, Tip4p, Tip5p, OPC, etc.? Currently, acpype can only handle conversion of the 3 point water models, if I'm not mistaken. Thanks!

**Comment by alanwilter** [comment]
I wish I could but I honestly don't have the time. There's also ff19SB with CMAP that I'd love to adapt but, again, no time.

**Comment by thepineapplepirate** [comment]
I hear you man. Happy to contribute to the code if I can find the script that does this.
