### ISSUE TITLE
link to openbabel in read me its not working use http://openbabel.org/

### ISSUE THREAD

**Issue by pippo1990** [alanwilter/acpype#126]
link to openbabel in read me its not working use http://openbabel.org/

**Comment by alanwilter** [comment]
Fixed, thanks!

**Comment by pippo1990** [comment]
Hi could you be so kind and have a look at https://bioinformatics.stackexchange.com/a/22895/10049  and see why I had to change parser_args.py  to have my script using acpype.cli ([h](https://acpype.readthedocs.io/en/latest/_autosummary/acpype.cli.html) work ( I got issues with spaces in input passed by acpype to ambertools)
