### ISSUE TITLE
Not able to generate charmm output

### ISSUE THREAD

**Issue by bhargavchava97** [alanwilter/acpype#14]
Hello there,

According to the documentation, this code should be able to generate charmm files. However, I am not able to see any charmm related file in the .acpype folder. Are there any dependencies needed to generate charmm output? 

P.S. This is an excellent tool to extract amber ff parameters and it would be even more awesome if it could output lammps related data. Thanks for your efforts.

**Comment by lkagami** [comment]
Hi,
How did you install acpype? 
Thanks,
Luciano

**Comment by bhargavchava97** [comment]
> Hi,
> How did you install acpype?
> Thanks,
> Luciano

You probably need to install antechamber first. To install acpype, open the acpype folder in shell and type this command ln -s $PWD/acpype.py /usr/local/bin/acpype. This is all explained in the README file.

**Comment by lkagami** [comment]
This is the problem, the versions for Ambertools above 18 are without the charmmgen function. My suggestion is to delete  your ambertools folder, remove the path in .bashrc, also remove /usr /local/bin /acpype. After install using the pip command:
pip install git+https: //github.com/alanwilter/acpype.git
Thank you so much for use Acpype.
Bests,
Luciano

**Comment by bhargavchava97** [comment]
I will try that.

Thank you
