### ISSUE TITLE
missing dihedral param in CNS params for cyclopropyl

### ISSUE THREAD

**Issue by mieczyslaw** [alanwilter/acpype#21]
I am using `acpype 2020.05.27.16.15` from conda-forge.

I have some issues with CNS param file generated for the small molecule containing cyclopropyl, see e.g. 4YY in https://www.rcsb.org/structure/5nvx

Adding manually the line for `DIHEdral   cxY   cxY   cxY   cxY` seems to solve the issue. 

Not sure if it is missed by `acpype`, `antechamber` doesn't deal with it or there is a reason to not to include it?

**Comment by alanwilter** [comment]
Where do you add `DIHEdral cxY cxY cxY cxY`?

**Comment by alanwilter** [comment]
Closing since I didn't have any follow up.
