### ISSUE TITLE
 Atomtype IP not found

### ISSUE THREAD

**Issue by dvdvbrn** [alanwilter/acpype#22]
Hello,

I am using ACPYPE v. 2020-10-24T12:16:34CEST to convert Amber topology containing Na+/Cl- ions into GMX topology. Upon running grompp I receive error: 
 
`ERROR 1 [file try1_GMX.top, line 19895]:
  Atomtype IP not found`

When I go to the line 19895 it looks like this:

`[ atoms ]
  ; id_    at type res nr  residu name     at name  cg nr  charge   mass
    1       IP      1          NA+         NA+       1      1     22.9898`

Question: what did go wrong? Is this something with my files, or with my current version installation?

Thanks!!!

**Comment by alanwilter** [comment]
Thanks for spotting this, it's legacy code and I think I have rooted out the problem, however, I need to test. Could you send you input files so I can try here, use my email please `alanwilter _at_ gmail _dot_ com`.

**Comment by alanwilter** [comment]
Fixed
