### ISSUE TITLE
different atom types | `-water` flag 

### ISSUE THREAD

**Issue by DavidCdeB** [alanwilter/acpype#49]
Thanks for this program. 
I would like to model in water, the following molecule: 4-nitrophenolate (PNP1):

![pnp1](https://user-images.githubusercontent.com/18029016/143072868-10db186a-c156-4188-af22-b31661d9f3e2.png)
Since it is charged, I'm utilizing the `-n -1` flag. 

I'm also using `gaff2` and the default charge method (bcc, i.e. `-c bcc`):

In summary:

`]$ acpype -a gaff2 -i PNP1.pdb -c bcc -n -1 -b PNP1`

Three files are generated (see them here: https://github.com/DavidCdeB/Files , uploaded as well the `PNP1.pdb` ):

> PNP1_GMX.gro
> PNP1_GMX.top
> PNP1_GMX.itp
>  PNP1.pdb

Since there are several carbon(atom) types, i.e. 
a) C bonded to nitro group, 
b) and C-Sp2, 

as well as several oxygen(atom) types: 
a) O bonded to Csp2 
b) and O bonded to =N

**1.** I'm wondering whether those quite different carbon and oxygen (atom) types have been correctly interpreted in `PNP1_GMX.itp` ?

**2.** I'm wondering whether there's a way of acpype-ing `-water tip3p` so that the `PNP1_GMX.top` contains the solvent information, as well as generating the `tip3p.itp` in the current working directory  ?

Many thanks.

**Comment by alanwilter** [comment]
I can't answer 1). ACPYPE/ANTECHAMBER try the best they can. At the end of the day, it's up to you to check, by research, test, simulations etc. if your model is good enough. 
If you don't see any worrying warnings with `-d` option than I'd go ahead.

For 2), nope, that step you need to do following Gromacs instructions (plenty of tutorials online). I do have some tutorials myself but they are not up to date so they may add more confusion than help, especially if you're new to Gromacs.
I need to time to review those tutorials which, unfortunately, I don't have for the moment. I'll let you know when I have something but, please, don't hold your breath.
