### ISSUE TITLE
Does Acpype perform Ligand Restraint?

### ISSUE THREAD

**Issue by gundalav** [alanwilter/acpype#67]
Hi Alan, 

This is not an issue, but general question on this great tool. 

I can successfully execute the excellent [Tutorial Using ACPYPE for GROMACS](https://github.com/alanwilter/acpype/wiki/Tutorial-Using-ACPYPE-for-GROMACS#an-example-illustrating-how-to-use-acpype-with-gromacs).

I wonder if ACPYPE as executed in that tutorial also performs Ligand Restraint. 
The  Ligand Restraint I refer to is as described in [GROMACS Protein-Ligand equilibration tutorial](http://www.mdtutorials.com/gmx/complex/06_equil.html).

However, I noticed that under `Ligand.acpype/` directory, one can find `posre_Ligand.itp` file. 
I'm not sure if it is the one and if it's actually used in final output.

Thanks and hope to hear from you again.

G.V.

**Comment by alanwilter** [comment]
It does, see #61. The `posre_lig.itp` created is exactly what you need, just adapt you `top` and `mdp` files accordingly.

**Comment by gundalav** [comment]
> It does, see #61. The `posre_lig.itp` created is exactly what you need, just adapt you `top` and `mdp` files accordingly.

Thanks for the quick reply. How can I adapt `posre_Ligand.itp` to the. `top` and `mdp` file?
