### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp'

### ISSUE THREAD

**Issue by yipy0005** [alanwilter/acpype#74]
Hi, when I was running the command: `acpype -i ligand.mol2 -n 0 -a gaff -c bcc`, and I encountered an error: `FileNotFoundError: [Errno 2] No such file or directory: 'tmp'`.

What can I do to resolve the error?

**Comment by alanwilter** [comment]
Did you read the help (-h). Did you see the log? Did you try -d? You don't even tell me which version you're using.

So if you need help, first save me the guesswork and provide the minimum information.
