### ISSUE TITLE
Unable to achieve self consistency to the tolerances specified 

### ISSUE THREAD

**Issue by azbven** [alanwilter/acpype#78]
I am receiving the following error for my molecules, here I am requesting to provide valuable suggestions to solve this issue. 

acpype -i UNK.mol2

----------------------------
QMMM: ERROR!
QMMM: Unable to achieve self consistency to the tolerances specified
QMMM: No convergence in SCF after   1000 steps.
-------------------------input file 

 
@<TRIPOS>MOLECULE

UNK.pdb
 48 51 0 0 0
SMALL
GASTEIGER

@<TRIPOS>ATOM
      1  C1        91.8720   86.3490  101.7550 C.3   900  UNK900      0.1680
      2  O1        92.8720   86.4820  102.7180 O.3   900  UNK900     -0.3456
      3  C2        94.0700   86.9280  102.0880 C.3   900  UNK900      0.1133
      4  C3        94.0690   86.2010  100.7410 C.3   900  UNK900      0.1135
      5  C4        92.6100   85.7470  100.5280 C.3   900  UNK900      0.1286
      6  C5        95.2870   86.6800  102.9920 C.3   900  UNK900      0.0836
      7  O2        94.4630   87.1190   99.7350 O.3   900  UNK900     -0.3864
      8  O3        92.5130   84.3190  100.5360 O.3   900  UNK900     -0.3847
      9  O4        95.8940   87.9200  103.2940 O.3   900  UNK900     -0.3246
     10  N1        91.2350   87.7150  101.5010 N.ar  900  UNK900     -0.2689
     11  C6        90.2010   87.8410  100.5180 C.ar  900  UNK900      0.3525
     12  N2        89.6240   89.1100  100.3190 N.ar  900  UNK900     -0.1726
     13  C7        89.9820   90.1130  101.0330 C.ar  900  UNK900      0.1739
     14  C8        90.9680   89.9820  102.0930 C.ar  900  UNK900      0.0744
     15  C9        91.5450   88.7970  102.3150 C.ar  900  UNK900      0.0294
     16  O5        89.8350   86.8500   99.8870 O.2   900  UNK900     -0.2444
     17  N3        89.5020   91.4690  100.9360 N.ar  900  UNK900     -0.2242
     18  C10       90.0490   92.2450  101.7840 C.ar  900  UNK900      0.0844
     19  S1        91.2330   91.4950  102.9060 S.2   900  UNK900     -0.0687
     20  P1        97.1970   88.5220  102.3830 P.3   900  UNK900      0.2182
     21  O6        96.8800   88.3190  100.9360 O.2   900  UNK900     -0.5170
     22  O7        97.4810   89.8910  102.8550 O.co2 900  UNK900     -0.4371
     23  O8        98.4290   87.4420  102.8400 O.3   900  UNK900     -0.2702
     24  P2        99.5330   87.1520  104.1140 P.3   900  UNK900      0.2206
     25  O9       100.9760   87.9480  103.6900 O.3   900  UNK900     -0.3141
     26  O10       99.0310   87.7560  105.3750 O.co2 900  UNK900     -0.4370
     27  O11       99.8220   85.6890  104.1360 O.co2 900  UNK900     -0.5169
     28  P3       102.0060   88.3390  102.4860 P.3   900  UNK900     -0.0068
     29  O12      101.4170   89.5190  101.7380 O.co2 900  UNK900     -0.5767
     30  O13      102.1570   87.1190  101.5950 O.co2 900  UNK900     -0.6374
     31  O14      103.3130   88.7190  103.1710 O.co2 900  UNK900     -0.5767
     32  C11       89.7780   93.7350  101.8610 C.3   900  UNK900      0.0079
     33  C12       88.3670   94.2730  101.9150 C.3   900  UNK900     -0.0437
     34  C13       89.2720   94.4120  103.1160 C.3   900  UNK900     -0.0437
     35 H          91.0559   85.7160  102.0346 H     900  UNK900      0.0867
     36 H          94.1245   87.9834  101.9206 H     900  UNK900      0.0647
     37 H          94.7399   85.3681  100.7084 H     900  UNK900      0.0647
     38 H          92.2052   86.0644   99.5898 H     900  UNK900      0.0665
     39 H          95.9885   86.0508  102.4851 H     900  UNK900      0.0591
     40 H          94.9750   86.1998  103.8958 H     900  UNK900      0.0591
     41 H          93.8678   87.8848   99.7450 H     900  UNK900      0.2100
     42 H          92.8687   83.9754  101.3705 H     900  UNK900      0.2101
     43 H          92.2188   88.6863  103.0888 H     900  UNK900      0.0824
     44 H          90.6277   93.8747  101.2259 H     900  UNK900      0.0369
     45 H          87.5379   93.5973  101.9456 H     900  UNK900      0.0272
     46 H          87.7930   94.9509  101.3184 H     900  UNK900      0.0272
     47 H          89.6485   95.3743  103.3938 H     900  UNK900      0.0272
     48 H          89.2062   94.1398  104.1487 H     900  UNK900      0.0272
@<TRIPOS>BOND
     1     7     4    1
     2    16    11    2
     3    12    11   ar
     4    12    13   ar
     5    11    10   ar
     6     5     8    1
     7     5     4    1
     8     5     1    1
     9     4     3    1
    10    21    20    2
    11    17    13   ar
    12    17    18   ar
    13    13    14   ar
    14    10     1    1
    15    10    15   ar
    16    30    28    2
    17    29    28    1
    18     1     2    1
    19    18    32    1
    20    18    19   ar
    21    32    33    1
    22    32    34    1
    23    33    34    1
    24     3     2    1
    25     3     6    1
    26    14    15   ar
    27    14    19   ar
    28    20    23    1
    29    20    22    1
    30    20     9    1
    31    28    31    1
    32    28    25    1
    33    23    24    1
    34     6     9    1
    35    25    24    1
    36    24    27    2
    37    24    26    1
    38     1    35    1
    39     3    36    1
    40     4    37    1
    41     5    38    1
    42     6    39    1
    43     6    40    1
    44     7    41    1
    45     8    42    1
    46    15    43    1
    47    32    44    1
    48    33    45    1
    49    33    46    1
    50    34    47    1
    51    34    48    1

**Comment by alanwilter** [comment]
This is a `SQM` (`Antechamber`) issue. Please, you'll need [Amber Mailing](http://lists.ambermd.org/mailman/listinfo) to get help.
