### ISSUE TITLE
multiple chain protein 

### ISSUE THREAD

**Issue by Christinele14** [alanwilter/acpype#79]
I successfully prepared the amber topology for the complex 1A0Q (https://www.rcsb.org/structure/1A0Q). However, when I used acpype to generate the Gromacs topology, it seemed that two chains in my protein are merged into one. It seemed weird. So could you please take a look at it? Thank you.

**Comment by alanwilter** [comment]
If you only could show me the steps, in detail, that you did...

But I suspect you didn't cap your chains with N and C terminals while using `tleap`.

**Comment by Christinele14** [comment]
Yeap. Here is my tleap.in file. 
Yes, I guess I have to add the chain information inside tleap. Could you please take a look and suggest how could I add chain information inside so that two chains could be identified? Thank you in advance.

`source oldff/leaprc.ff99SB
source leaprc.gaff2
source leaprc.water.tip3p 

loadamberprep 1a0q_ligand_h_cleaned.prepi
loadamberparams 1a0q_ligand_h_cleaned.frcmod
mol = loadpdb cat_1a0q_complex.pdb

solvatebox mol TIP3PBOX 8 
addions mol Cl- 0 
saveamberparm mol 1a0q_complex.prmtop 1a0q_complex.inpcrd 
quit `

**Comment by alanwilter** [comment]
Have a look here https://github.com/alanwilter/acpype/wiki/Tutorial-NAMD

But your protein has problems. Have you seen its 3D?
https://www.rcsb.org/3d-view/1A0Q

Have you read the PDB header?

```pdb
REMARK 465 MISSING RESIDUES                                                     
REMARK 465 THE FOLLOWING RESIDUES WERE NOT LOCATED IN THE                       
REMARK 465 EXPERIMENT. (M=MODEL NUMBER; RES=RESIDUE NAME; C=CHAIN               
REMARK 465 IDENTIFIER; SSSEQ=SEQUENCE NUMBER; I=INSERTION CODE.)                
REMARK 465                                                                      
REMARK 465   M RES C SSSEQI                                                     
REMARK 465     ASP L     1                                                      
REMARK 465     GLU H     1                                                      
REMARK 465     GLY H    98                                                      
REMARK 465     ARG H    99                                                      
REMARK 465     SER H   100                                                      
REMARK 465     ASN H   100A                                                     
REMARK 465     GLY H   127                                                      
REMARK 465     SER H   128                                                      
REMARK 465     ALA H   129                                                      
REMARK 465     ALA H   130                                                      
REMARK 465     GLN H   131                                                      
REMARK 465     THR H   132                                                      
REMARK 465     ASN H   133                                                      
```

`tleap` already does the terminals accordingly, but there are several things to pay attention. You likely need to learn `tleap` properly. But first you really need to know your protein and your input PDB.

I really doubt we have a `ACPYPE` issue here.
