### ISSUE TITLE
wrong converted charge

### ISSUE THREAD

**Issue by qinghualiao** [alanwilter/acpype#80]
Hello, 

Yesterday, I used acpype (installed via conda) to convert amber topology to gmx one,
and I found one wrong charge for NE2 (GLN).
(| ACPYPE: AnteChamber PYthon Parser interfacE v. 2022.6.6 (c) 2022 AWSdS |)

In Amber 14SB force field, the charge (NE2, GLN) is -0.9407, but the converted one is -0.947455. 

However, the charge is correct with run_acpype.py from github. 

I don't know what went wrong. 

All the best,
Qinghua

**Comment by qinghualiao** [comment]
Actually, with run_acpype.py, the charge is not correct either in another run. 

I found that acpype (acpype, run_acpype.py) processed the topology file generated by tleap directly correctly, 
the error happened with a modified topology file by parmed (changed charges for GLU residues for QM/MM simulation). However, 
parmed did the conversion on the modified topology correctly. 

All the best,
Qinghua

**Comment by alanwilter** [comment]
Run with -d (debug mode). It's likely the charge balance routined to zero the total charge of your system. It will take the highest absolute partial charge and modify it.

This is done in order to absolutely zero the total charges for GMX and avoid e.g. PME artefacts etc.

**Comment by qinghualiao** [comment]
Hello Alan, 

Thanks a lot for your comments, this makes sense now. 
I will use acpype to do the conversion on the initial Amber topology file. 

All the best,
Qinghua

> Run with -d (debug mode). It's likely the charge balance routined to zero the total charge of your system. It will take the highest absolute partial charge and modify it.
> 
> This is done in order to absolutely zero the total charges for GMX and avoid e.g. PME artefacts etc.
