### ISSUE TITLE
acpype error

### ISSUE THREAD

**Issue by sjdyz** [alanwilter/acpype#83]
Hi guys 
I have this problem,
anyone can help me please?

ACPYPE: AnteChamber PYthon Parser interfacE v. 2022.8.25 (c) 2022 AWSdS |
===========================================================================
WARNING: no charge value given, trying to guess one...
==> ... charge set to 0
==> ... converting pdb input file to mol2 input file
==> * Babel OK *
==> Executing Antechamber...
ERROR: ++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR:
Welcome to antechamber 21.0: molecular input file processor.

The atom type is set to gaff2; the options available to the -at flag are
 gaff, gaff2, amber, bcc, and sybyl.
Info: Finished reading file (Lig70.mol2); atoms read (120), bonds read (130).
Info: Determining atomic numbers from atomic symbols which are case sensitive.
Running: /home/sajad/acpype/acpype/amber21-11_linux/bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac
Warning: The assigned bond types may be wrong, please :
(1) double check the structure (the connectivity) and/or
(2) adjust atom valence penalty parameters in APS.DAT, and/or
(3) increase PSCUTOFF in define.h and recompile bondtype.c
 (be cautious, using a large value of PSCUTOFF (>100) will
 significantly increase the computation time).

Running: /home/sajad/acpype/acpype/amber21-11_linux/bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff2
Info: Total number of electrons: 721; net charge: 0
Info: The number of electrons is odd (721).
 Please check the total charge (-nc flag) and spin multiplicity (-m flag).

Running: /home/sajad/acpype/acpype/amber21-11_linux/bin/sqm -O -i sqm.in -o sqm.out
/home/sajad/acpype/acpype/amber21-11_linux/bin/wrapped_progs/antechamber: Fatal Error!
Cannot properly run "/home/sajad/acpype/acpype/amber21-11_linux/bin/sqm -O -i sqm.in -o sqm.out".

ERROR: ++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Antechamber failed
ERROR: ++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Cannot open file (Lig70_bcc_gaff2.mol2) with mode (r).
No such file or directory
ERROR: ++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Parmchk failed
ERROR: Tleap failed
==> Removing temporary files...
ERROR: ACPYPE FAILED: [Errno 2] No such file or directory: 'Lig70_AC.prmtop'
Traceback (most recent call last):
  File "/home/sajad/acpype/acpype/cli.py", line 140, in init_main
    molecule.createMolTopol()
  File "/home/sajad/acpype/acpype/topol.py", line 1116, in createMolTopol
    self.topFileData = open(self.acTopFileName).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'Lig70_AC.prmtop'
Total time of execution: 1s

**Comment by alanwilter** [comment]
You need to check what is the net charge of you system. The `sqm` routine won't run it's telling you why: you have 721 electrons, this cannot be net charge 0. `ACPYPE` try to guess the net charge but this sometimes won't work.
