### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by wenyan4work** [alanwilter/acpype#88]
when computing distance, this seems incorrect.

https://github.com/alanwilter/acpype/blob/f0bdfe831ac82fee4569bb9834a0d26b84293560/acpype/utils.py#L63

**Comment by alanwilter** [comment]
What would be wrong?

If you think it's missing `sqrt` here, that's not the case, `dist2` is keep _squared_ on purpose.

**Comment by wenyan4work** [comment]
> What would be wrong?
> 
> 
> 
> If you think it's missing `sqrt` here, that's not the case, `dist2` is keep _squared_ on purpose.

(c1[0] - c2[0]) ** 2 is added twice in there

**Comment by alanwilter** [comment]
Indeed! Thanks for spotting that. Fortunately it was not used in any critical routine but only to warn if 2 atoms were too close or too distant.
It will be fixed for next release.
