### ISSUE TITLE
atom type does not exist in parmchk.dat

### ISSUE THREAD

**Issue by suneelbvs** [alanwilter/acpype#89]
Hi,

Im getting error with parmchk2 step.

Atom type of 12 does not exist in PARMCHK.DAT

Is it something to do with atom typing or input (charged molecule? : i have specified -nc option). Can you please suggest how to i rectify this issue?

**Comment by alanwilter** [comment]
What's your input file? You're likely naming wrongly an atom.

**Comment by suneelbvs** [comment]
Here are the steps that followed:

1. reduce lig.pdb > lig_h.pdb antech 

2. antechamber -i lig_h.pdb -fi pdb -o lig.mol2 -fo mol2 -c bcc -s 2 -nc 2 - j 5 -at bcc -dr no
(-nc = 2 added to address two carboxylate groups)

and my input for parmchk2 step is mol2 prepared from antechamber.

3. parmchk2 -i lig.mol2 -f mol2 -o lig.frcmod 


Did i miss anything here?. Please suggest.

Thanks in advance.

**Comment by alanwilter** [comment]
Why are not using acpype?
