### ISSUE TITLE
Is there a way to control the threads?

### ISSUE THREAD

**Issue by Dead-fisher** [alanwilter/acpype#91]
Hi there,

I am using `acpype` to parameterize the small molecules on a HPC cluster. It seems that `acpype` uses all threads on a computational node automatically when doing the QM calculation. Is there a way to control the numer of threads used by `acpype`?

Thanks

**Comment by alanwilter** [comment]
Do `export OMP_NUM_THREADS=1`, or whatever number of cpus you'd like, but usually just 1 works fine.

**Comment by Dead-fisher** [comment]
Thanks!
One more quick question, Do you have an good idea about how the number of cpus accelerate the QM computation in acpype? Is it linear scalable?

**Comment by alanwilter** [comment]
It's SQM and the parallelisation does not not scale, so use 1 cpu.
