### ISSUE TITLE
Is the GMX_OPLS still experimental?

### ISSUE THREAD

**Issue by BJWiley233** [alanwilter/acpype#92]
Hi,

I get atom types `opls_x` with 0.0 mass for the OPLS parameters.  Is this still [experimental](https://gromacs.org-gmx-users.maillist.sys.kth.narkive.com/OUb5Xth3/gmx-users-after-using-acpype-gromacs-opls-itp-file-generated-an-atom-type-like-opls-x-with-mass-0)?  Should we only use [mktop](https://github.com/aar2163/MKTOP/blob/master/mktop.pl) or ligpargen?

**Comment by alanwilter** [comment]
Indeed, don't use ACPYPE for OPLS unfortunately.

**Comment by PythonFZ** [comment]
> Indeed, don't use ACPYPE for OPLS unfortunately.

Is this still being worked on?

**Comment by alanwilter** [comment]
No, OPLS won't be added to ACPYPE.
