### ISSUE TITLE
conversion of Amber files to gromacs

### ISSUE THREAD

**Issue by Pz-Maajid** [alanwilter/acpype#98]
I am converting the two files that is UNL.parm7 and UNL.rst7 , which I got from ambertools, to gromacs using acpype. But the gro file which I got from this conversion has some bond missing in it when I am opening it in VMD  .I want to know the reason ,why this is happening . .

**Comment by riquri** [comment]
A .gro file does not contain bond information. Thus, VMD infers and draws the presence or absence of a bond by the distance of the atoms. The distance between pairs of atoms may be longer than the cut-off.
Could you check the distance of these missing bonds?

**Comment by Pz-Maajid** [comment]
> A .gro file does not contain bond information. Thus, VMD infers and draws the presence or absence of a bond by the distance of the atoms. The distance between pairs of atoms may be longer than the cut-off. Could you check the distance of these missing bonds?



> A .gro file does not contain bond information. Thus, VMD infers and draws the presence or absence of a bond by the distance of the atoms. The distance between pairs of atoms may be longer than the cut-off. Could you check the distance of these missing bonds?
.
It is 1.93 and 1.8 A for the missing bonds .Can you please tell how to solve the issue .

**Comment by Pz-Maajid** [comment]
It is 1.93 and 1.8 A for the missing bonds .Can you please tell how to solve the issue .

**Comment by alanwilter** [comment]
How? I don't have the input files.
